# This file was generated by GoReleaser. DO NOT EDIT.
cask "pre" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "5e87799f473edb178e50281962591712977455d74723939c11bba0c80a69548f"
      url "https://github.com/Z-Mackintosh/pre/releases/download/v#{version}/pre_darwin_arm64.tar.gz",
        verified: "github.com/Z-Mackintosh/pre"
    end
    on_intel do
      sha256 "5f27a4f1107af8d78e247d8b6061ad49b970ba78a2e3685e68ba82ded02efb6d"
      url "https://github.com/Z-Mackintosh/pre/releases/download/v#{version}/pre_darwin_amd64.tar.gz",
        verified: "github.com/Z-Mackintosh/pre"
    end
  end
  on_linux do
    on_arm do
      sha256 "9fb6f5fac4d3abbb24b0e86b30e2c31f75ab021c05eec3e99543d87479f1f2f8"
      url "https://github.com/Z-Mackintosh/pre/releases/download/v#{version}/pre_linux_arm64.tar.gz",
        verified: "github.com/Z-Mackintosh/pre"
    end
    on_intel do
      sha256 "9725e80a8ab3aa26b88326ffdc4bd42e4732c869ae3b6933d9d6e3d5d0d34949"
      url "https://github.com/Z-Mackintosh/pre/releases/download/v#{version}/pre_linux_amd64.tar.gz",
        verified: "github.com/Z-Mackintosh/pre"
    end
  end

  name "pre"
  desc "Package single-page HTML slides and narration audio into one portable .pre file"
  homepage "https://github.com/Z-Mackintosh/pre"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pre"

  # No zap stanza required
end
