# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pre < Formula
  desc "Package single-page HTML slides and narration audio into one portable .pre file"
  homepage "https://github.com/Z-Mackintosh/pre"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Z-Mackintosh/pre/releases/download/v0.1.0/pre_darwin_amd64.tar.gz"
      sha256 "fafe34abe0fbaba15dc7d092c36f00406d6fcb8415c43e62778f01d3bbb08f91"

      define_method(:install) do
        bin.install "pre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Z-Mackintosh/pre/releases/download/v0.1.0/pre_darwin_arm64.tar.gz"
      sha256 "01f7ee9d17a1263fa525b327fd114d1d479ae5d828e58308a2404fa029adc574"

      define_method(:install) do
        bin.install "pre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Z-Mackintosh/pre/releases/download/v0.1.0/pre_linux_amd64.tar.gz"
      sha256 "97550feabe6d6956e8dc538b41f16187a9a40604de3ab1e4b63fa610e3424190"
      define_method(:install) do
        bin.install "pre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Z-Mackintosh/pre/releases/download/v0.1.0/pre_linux_arm64.tar.gz"
      sha256 "da3ff125f8d24563329934a541143c22dbd4023fef6cd57b21c7d91c35349832"
      define_method(:install) do
        bin.install "pre"
      end
    end
  end
end
